from . import main
from . import players
from . import matches
from . import tournaments
from . import auth
from . import api
from . import startup
from . import uploads
from . import users
from . import news
from . import registrations
