"""add division standings_up_to_date

Revision ID: 37d0294618a5
Revises: fb3ca462fc52
Create Date: 2026-07-09 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "37d0294618a5"
down_revision = "fb3ca462fc52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("divisions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("standings_up_to_date", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###

    # Backfill existing rows to True so pre-existing divisions don't appear
    # stale on first deploy — the app-level default=True only applies to
    # new INSERTs, not existing rows.
    op.execute("UPDATE divisions SET standings_up_to_date = true")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("divisions", schema=None) as batch_op:
        batch_op.drop_column("standings_up_to_date")
