name: Build and Deploy to GCE

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/porto-padel-league:latest
        platforms: linux/amd64

    - name: Deploy on GCE
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USER }}
        key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/porto-padel-league:latest
          sudo docker stop ppl || true && sudo docker rm ppl || true
          sudo docker run -d --name ppl -p 5000:80 ${{ secrets.DOCKERHUB_USERNAME }}/porto-padel-league:latest

    - name: Copy backup script to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USER }}
        key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
        source: "scripts/backup.sh"
        target: "/home/${{ secrets.GCE_USER }}//backup.sh"
        strip_components: 1
        overwrite: true

    - name: Setup cron job for backup script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCE_HOST }}
        username: ${{ secrets.GCE_USER }}
        key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
        script: |
          chmod +x /home/${{ secrets.GCE_USER }}/backup.sh

          (crontab -l 2>/dev/null | grep -v backup.sh; echo "0 3 * * * /home/${{ secrets.GCE_USER }}/backup.sh") | crontab -

